### ISSUE TITLE
29 versus 30 simulated samples

### ISSUE THREAD

**Issue by peterjc** [lmathon/eDNA--benchmark_pipelines#45]
Quoting Mathon *et al.* (2021) Benchmarking bioinformatic tools for fast and accurate eDNA metabarcoding species identification https://doi.org/10.1111/1755-0998.13430

> We simulated 29 different species assemblages, hereafter designed as “samples”, using the program Grinder (Angly et al., 2012)
> ...
> Each simulated assemblage was replicated 12 times, with the same species and abundance composition, to mimic PCR replicates variability.

This matches the sets of 29 files here, for example ``tag_sample01.fasta`` though ``tag_sample29.fasta``:

https://github.com/lmathon/metabarcoding_data_simulation/tree/master/Inputs

However, ``benchmark_simulated_dataset/02_demultiplex/Tags.fasta`` has 360 entries, 30 samples with 12 replicates named ``S1-01`` though ``S30-12``:

https://github.com/lmathon/eDNA--benchmark_pipelines/blob/master/benchmark_simulated_dataset/02_demultiplex/Tags.fasta

Based on this commit in the data generation repository, it appears there were originally 30 samples but sample 8 was deleted and the rest renumbered as 1 to 29:

https://github.com/lmathon/metabarcoding_data_simulation/commit/1a0944bca86792b055b4b00e0df83fab64de8803

Should the entries for Sample 8 in ``Tags.fasta`` in the benchmark repository also have been removed (and the rest renumbered)?

**Comment by peterjc** [comment]
There are also on 29 samples here:

https://github.com/lmathon/eDNA--benchmark_pipelines/tree/master/benchmark_simulated_dataset/00_Input_data/species_abundance_per_sample

**Comment by peterjc** [comment]
This file has 29 samples, and the MID barcoding tags too:

https://github.com/lmathon/eDNA--benchmark_pipelines/blob/master/benchmark_simulated_dataset/00_Input_data/sample_description_file.txt

The MID barcodes here are consistent with ``Tags.fasta`` needing sample 8 to be deleted, and the later samples renumbered.

**Comment by lmathon** [comment]
Hi,

Yes you are right, thank you for spotting this mistake.
I updated the tag.fasta files to match the 29 samples.

Should be ok now!

**Comment by peterjc** [comment]
Commit e5fb1c1ea7a920937a5934555bf0804029c2e892 does seem to have fixed this, thank you.
